### ISSUE TITLE
Quote retrieval fails on Windows 10

### ISSUE THREAD

**Issue by realrosid** [alex314159/PerlFinanceQuoteBloomberg#4]
With the bug and solution for Windows 10 I posted here:
http://gnucash.1415818.n4.nabble.com/Re-No-stock-quote-for-LU1233758587-tc4693298.html#none
I was able to retrieve Bloomberg quotes. Since a few months it stopped working.

Using 

gnc-fq-dump bloomberg 1938:HK 

generates the following error:

Can't call method "attr" on an undefined value at C:/Strawberry/perl/site/lib/Finance/Quote/Bloomberg.pm line 47, <DATA> line 1.

This happens with or without the changes described in the link above (e.g.changing  @price_array[0] --> $price_array[0] and so on)

**Comment by realrosid** [comment]
Testing with gnc-fq-helper with the above mentioned changes (e.g.changing @price_array[0] --> $price_array[0] and so on) I get the following result:

C:\Program Files (x86)\gnucash\bin>perl gnc-fq-helper
(bloomberg "1938:HK")
Parsing of undecoded UTF-8 will give garbage when decoding entities at C:/Strawberry/perl/vendor/lib/HTML/TreeBuilder.pm line 108, <> line 1.
Can't call method "attr" on an undefined value at C:/Strawberry/perl/site/lib/Finance/Quote/Bloomberg.pm line 47, <> line 1.

**Comment by pfsq** [comment]
Uncomment line 36 and see what `perl gnc-fq-dump bloomberg 1938:HK` outputs. Most likely, Bloomberg is flagging you for violation of their terms of service; asking you to verify you are not a robot... which is obviously not possible.

**Comment by realrosid** [comment]
You are right, see below. Bloomberg flagged me for violation of their TOS.
What can I do about this?

C:\Program Files (x86)\gnucash\bin>perl gnc-fq-dump -v bloomberg 1938:HK
<html>
<head>
    <title>Terms of Service Violation</title>
    <style rel="stylesheet" type="text/css">
        .container {
            font-family: Helvetica,Arial,sans-serif;
        }
    </style>
    <!ÔÇô Google Recaptha JS file ->
    <script src="https://www.google.com/recaptcha/api.js"></script>
    <!ÔÇô PerimeterX JS snippet ->
    <script type="text/javascript">
        (function () {
            window._pxAppId = 'PX8FCGYgk4';
            // Custom parameters
            // window._pxParam1 = "<param1>";
            var p = document.getElementsByTagName('script')[0],
                s = document.createElement('script');
            s.async = 1;
            s.src = '//client.perimeterx.net/PX8FCGYgk4/main.min.js';
            p.parentNode.insertBefore(s, p);
        }());
    </script>
    <noscript>
        <div style="position:fixed; top:0; left:0;" width="1" height="1">
            <img src="//collector-PX8FCGYgk4.perimeterx.net/api/v1/collector/noScript.gif?appId=PX8FCGYgk4">
        </div>
    </noscript>
    <!ÔÇô Call back handler for reCaptcha and query string function->
    <script>
        var vid = getQueryString("vid");
        var uuid = getQueryString("uuid");

        function handleCaptcha(response) {
            var name = '_pxCaptcha';
            var expiryUtc = new Date(Date.now() + 1000 * 10).toUTCString();
            var cookieParts = [name, '=', btoa(JSON.stringify({
                r: response,
                v: vid,
                u: uuid
            })), '; expires=', expiryUtc, '; path=/'];
            document.cookie = cookieParts.join('');
            // after getting resopnse we want to reaload the original page requested
            var originalURL = getQueryString("url");
            var originalHost = window.location.host;
            window.location.href = window.location.protocol + "//" + originalHost + originalURL;
        }

        function getQueryString(name, url) {
            if (!url) url = window.location.href;
            name = name.replace(/[\[\]]/g, "\\$&");
            var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
                results = regex.exec(url);
            if (!results) return null;
            if (!results[2]) return '';
            if (name == "url") {
                results[2] = atob(results[2]);
            }
            return decodeURIComponent(results[2].replace(/\+/g, " "));
        }
    </script>
</head>
<body>
<div class="container">
    <!ÔÇô Customer messaging and logo ->
    <img style="margin-bottom: 40px;" src="https://www.bloomberg.com/graphics/assets/img/BB-Logo-2line.svg"
         width="310"/>
    <h1 class="text-center" style="margin: 0 auto;">Terms of Service Violation</h1>
    <p>Your usage has been flagged as a violation of our <a href="http://www.bloomberg.com/tos" target="_blank" rel="noopener noreferrer">terms of service</a>.
    </p>
    <p>
        For inquiries related to this message please <a href="http://www.bloomberg.com/feedback">contact support</a>.
        For sales
        inquiries, please visit <a href="http://www.bloomberg.com/professional/request-demo">http://www.bloomberg.com/professional/request-demo</a>
    </p>
    <h3 style="margin: 0 auto;">
        If you believe this to be in error, please confirm below that you are not a robot by clicking "I'm not a robot"
        below.</h3>
    <br>
    <!ÔÇô Google Recaptcha DIV element with PerimeterX data-sitekey ->
    <div style="width: 310px" class="g-recaptcha"
         data-sitekey="6Lcj-R8TAAAAABs3FrRPuQhLMbp5QrHsHufzLf7b" data-callback="handleCaptcha" data-theme="light"></div>
    <!ÔÇô Google Recaptcha DIV element with PerimeterX data-sitekey ->
    <br>
    <h3 style="margin: 0 auto;">Please make sure your browser supports JavaScript and cookies and
        that you are not blocking them from loading. For more information you can review the Terms of Service and Cookie
        Policy.</h3>
    <br>
    <!ÔÇô Display of Unique request ID for customer to reference ->
    <h3 id="block_uuid" style="margin: 0 auto; color: #C00;">Block reference ID: </h3>
    <script type="text/javascript">document.getElementById("block_uuid").innerHTML = "Block reference ID: " + uuid;</script>
</div>
</body>
<html>
Can't call method "attr" on an undefined value at C:/Strawberry/perl/site/lib/Finance/Quote/Bloomberg.pm line 47, <DATA> line 1.

**Comment by realrosid** [comment]
Is there anything I can do to still retrieve Bloomberg quotes?

**Comment by alex314159** [comment]
Unclear. I’d try and go to the page manually a few times and confirm that “I’m not a robot” and see if eventually they no longer ask you

If you’re running on a server you can change the server / use a different IP.

Also if any of these work you’ll probably need to download fewer quotes at once / less frequently so you do t get flagged again

**Comment by alex314159** [comment]
Actually I've had the same issue - I've committed a change where the script now pretends it's Mozilla. Seems to have solved the problem for now, try the new version.

**Comment by realrosid** [comment]
Thanks!
I tried it and it worked exactly one time before I got flagged again. Will try again this week and report back

**Comment by alex314159** [comment]
still working for me, weird. Maybe try different user agents. FWIW I'm only downloading about 10 quotes at a time, and every few days or so

**Comment by realrosid** [comment]
I am just trying to get 2 quotes. I tried switching the user agent to "Mozilla/4.0 (compatible; MSIE 5.0; Windows 95)", still no luck.
I am able to open the bloomberg quote website (Firefox, IE, Chrome) without a problem (no verification that I am not a robot needed), but as soon as I try getting the quote using perl I get the TOS violation return message. 
I am curious as to how they make the distinction between my browser (Firefox, IE or Chrome) and the perl script?

**Comment by alex314159** [comment]
I think you want to identify as a new browser - maybe check how your current browser identifies itself and use that. There are websites that tell you who you are

**Comment by realrosid** [comment]
I tried that as well but it didn't work. After waiting a day and trying again this morning it worked. As I only need 2 quotes from bloomberg every couple of days, I will leave it like that. Maybe they have a time limit where you can get a quote only every few seconds and get flagged if you try too often too fast.

**Comment by jbbandos** [comment]
I apologise for reopening this, but it is happening to me in Linux. First time I've used the module in months, and with the version I just downloaded today. :(
Uncommenting the "print" shows exactly the same robot detection page is the culprit.

**Comment by alex314159** [comment]
I'm having the similar problem on and off. I'm afraid Bloomberg have got smarter with their detection. Anecdotically it seems to work better when used from a cellular network (creating a HotSpot from your mobile). I'm afraid I don't understand Perl / web security enough - beyond changing the UserAgent, which didn't work for long, anyone has any idea what to do?

**Comment by realrosid** [comment]
I can confirm that behaviour. 
Whenever I try to get the quotes while I'm on wifi (home or work) I get an error. When I switch to mobile (using a build in 4g card) it works (sometimes). Maybe Bloomberg identifies large providers by IP range and blocks them and maybe they don't do that for mobile carriers?

**Comment by alex314159** [comment]
Can you try again - I've changed the header request - it works on my machine (for now!)

**Comment by pfsq** [comment]
On mine it works (for now).

**Comment by realrosid** [comment]
Can confirm, it works. I tried with 3 stocks multiple times, seems stable. Tried both manually and using GnuCash.
Thanks for the fix!

**Comment by jbbandos** [comment]
:( And again it doesn't work on mine. Once again with "<title>Bloomberg - Are you a robot?</title>"

**Comment by realrosid** [comment]
Still working for me. I am only retrieving 3 stock quotes using Bloomberg, but it still works.

**Comment by alex314159** [comment]
Working for me too - retrieving about 10 securities once a week. I wonder if Bloomberg also lock IPs if there are too many requests? Might be worth playing around with these lines and see if it helps:

      'User-Agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 
      'referrer' => 'https://www.google.com',
      'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
      #'Accept-Encoding' => 'gzip, deflate, br', 
      'Accept-Language' => 'en-US,en;q=0.9',
      'Pragma' => 'no-cache', );

**Comment by jbbandos** [comment]
I've tried with and without VPN, and have changed the user agent and accept language to those of my current chrome browser, and still no luck :(
Using the "https://www.bloomberg.com/quote/1938:HK" url on chrome on the same machine works perfectly. With and without VPN.

**Comment by alex314159** [comment]
Can you try two more things?
* ask for just one security on the command line: gnc-fq-dump bloomberg 1938:HK (in case it's a throttling issue if you ask for too many at the same time)
* do it over a cellular network (using your mobile to create a hotspot for instance). As that seemed to solve it in the past

**Comment by jbbandos** [comment]
Hi Alex, I was already doing it on the command line with a single security to make sure I wasn't hitting some throttling issue. I tried again, both on the "normal" wifi and over the cellular network, and still get the same issue.

**Comment by realrosid** [comment]
Hi Alex, is it possible that Bloomberg changed their site layout again? 
I can't retrieve any quotes and uncommenting line 45 in Bloomberg.pm returns what seems to be a valid HTML code, as far as I can tell.
I tested using D500:GR.

**Comment by alex314159** [comment]
Yes time variable has changed I’ll push change later or go to any page and search for time in the source

**Comment by realrosid** [comment]
That would be great if you could push a change. Thanks a lot!

**Comment by alex314159** [comment]
should be good now

**Comment by realrosid** [comment]
It works again. Thank you very much!

**Comment by realrosid** [comment]
Hi Alex,
did Bloomberg again change something? I can't get any quotes.
Thanks a lot for all your work!

**Comment by alex314159** [comment]
Pushed an update, try now. Bbg basically no longer providing date/time of quote.
